openapi: 3.0.3
info:
  title: User Subscription API
  version: 3.0.1
  description: |-
    This is a sample User Subscription API

paths:
  /api/external/user:
    get:
      summary: Get user information
      tags:
      - External user
      parameters:
        - name: user_id
          in: query
          schema:
            type: string
            minLength: 7
            maxLength: 7
          description: Unique user identifier #Seven characters long
          example: "3453255"
        - name: from
          in: query
          schema:
            type: integer
          description: Pagination start timestamp #Timestamp in nanoseconds
          example: 1628883600000
        - name: to
          in: query
          schema:
            type: integer
          description: Pagination end timestamp #Timestamp in nanoseconds
          example: 1628883600000
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 10
            maximum: 1000
            default: 1000 #default: 1000
          description: Limit to records returned
        - name: provider_id
          in: query
          schema:
            type: string
            minLength: 4
            maxLength: 4
            example: "2323"
          description: Unique identifier of the partner a user bound to
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
  /api/partner:
    get:
      summary: Get information
      tags:
        - Partner
      parameters:
        - name: provider_id
          in: query
          required: true
          description: Unique partner identifier
          schema:
            type: string
            minLength: 4
            maxLength: 4
            example: "2323"
        - name: status
          in: query
          schema:
            type: string
            enum:
            - active
            - stopped
          description: Partner operation state
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Partner"
components:
  schemas:
    Users:
      type: object
      required:
        - user_id
        - provider_id
        - status
        - type
        - zone
      properties:
        user_id:
          type: string
          example: "3453255"
        provider_id:
          type: string
          example: "2323"
        status:
          type: string
          enum:
            - active
            - inactive
            - idle
          description: User service state
        types:
          type: string
          enum:
            - basic
            - guest
            - company
            - advance
            - admin
        zone:
          type: string
          enum:
            - ru
            - us
            - gb
    Partner:
      type: object
      required:
        - provider_id
        - status
      properties:
        provider_id:
          type: string
          example: "2323"
        status:
          type: string
          enum:
            - active
            - stopped